### ISSUE TITLE
contentBinding is Superfluous

### ISSUE THREAD

**Issue by Undistraction** [dgeb/ember_data_example#37]
First, thanks for this very helpful project.

It seems that in contacts.hbs, explicitly setting the contentBinding is unnecessary:

```
{{view App.ContactInListView contentBinding="contact"}}
```

Works just as well using:

```
{{view App.ContactInListView}}
```

Can't work out how or why this is so though. Must be magic.

**Comment by dgeb** [comment]
It's a bit tricky. The sole reason for that `contentBinding` is to ensure that `isActive()` can be evaluated in `App.ContactInListView`. If you remove it, the active contact will no longer be highlighted, because the view won't have access to the contact.

The reason that the contacts still appear in the list properly is that the template `contact_in_list.hbs` has access to the `contact` var from its parent, and so it can evaluate:

```
{{#linkTo "contact" contact}}{{contact.fullName}}{{/linkTo}}
```

Some of these context differences between templates and views can be a bit subtle and confusing.

**Comment by Undistraction** [comment]
I have to say I'm really struggling with Ember. There is so much out there that is out of date or subtly wrong and very little in the way of best practices. I can see that Ember is a really great thing, but I'm not much enjoying learning it from the scraps I can find. Thanks again for this example. It's been really helpful.

**Comment by dgeb** [comment]
@1ndivisible  Take heart - Ember's 1.0 API stabilized just over a month ago. I think that you'll see a wave of new guides, tutorials and examples now that much of the churn is behind us. In fact, I'm just getting the tests in order for this project and will be doing a series of blog posts based on it soon.
